"""baseline: esquema inicial (users, spectra, zeolite_families, similarity_results, session_tokens)

Revision ID: 0ab5aaa1271c
Revises:
Create Date: 2026-08-09 17:16:30.183169

IMPORTANTE — cómo adoptar Alembic sin romper la BD existente:
El esquema ya existe en producción (creado con Base.metadata.create_all en
app/core/database.py:init_db, más el ALTER manual de migrate_users.py que ya
añadió role/verification_token). Esta migración representa ese mismo estado
final, para que cualquier BD NUEVA pueda crearse solo con Alembic.

  - BD nueva (vacía): `alembic upgrade head` — crea las 5 tablas desde cero.
  - BD de producción existente (ya tiene las tablas): NO correr `upgrade head`
    directamente — fallaría con "tabla ya existe". Correr en su lugar
    `alembic stamp head`, que registra esta revisión como aplicada sin
    ejecutar ningún DDL. A partir de ahí, todas las migraciones futuras
    (nuevas columnas, tablas) se generan con `alembic revision --autogenerate`
    y sí se aplican normalmente con `upgrade head`.
  - No se ha ejecutado `stamp head` contra la BD MySQL real desde este entorno
    (sin acceso a ella) — es la primera acción a tomar al desplegar esto.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab5aaa1271c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('zeolite_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('chemical_formula', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zeolite_families_code'), 'zeolite_families', ['code'], unique=True)
    op.create_index(op.f('ix_zeolite_families_id'), 'zeolite_families', ['id'], unique=False)
    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_session_tokens_id'), 'session_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_session_tokens_user_id'), 'session_tokens', ['user_id'], unique=False)
    op.create_table('spectra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=True),
    sa.Column('hydration_state', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.String(length=50), nullable=True),
    sa.Column('wavenumber_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spectra_id'), 'spectra', ['id'], unique=False)
    op.create_index(op.f('ix_spectra_user_id'), 'spectra', ['user_id'], unique=False)
    op.create_table('similarity_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_spectrum_id', sa.Integer(), nullable=False),
    sa.Column('search_method', sa.String(length=50), nullable=True),
    sa.Column('tolerance', sa.Integer(), nullable=True),
    sa.Column('range_min', sa.Integer(), nullable=True),
    sa.Column('range_max', sa.Integer(), nullable=True),
    sa.Column('top_n', sa.Integer(), nullable=True),
    sa.Column('family_filter', sa.String(length=50), nullable=True),
    sa.Column('use_windows', sa.Boolean(), nullable=True),
    sa.Column('selected_windows', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('total_spectra_searched', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('results_found', sa.Integer(), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['query_spectrum_id'], ['spectra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similarity_results_id'), 'similarity_results', ['id'], unique=False)
    op.create_index(op.f('ix_similarity_results_user_id'), 'similarity_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_similarity_results_user_id'), table_name='similarity_results')
    op.drop_index(op.f('ix_similarity_results_id'), table_name='similarity_results')
    op.drop_table('similarity_results')
    op.drop_index(op.f('ix_spectra_user_id'), table_name='spectra')
    op.drop_index(op.f('ix_spectra_id'), table_name='spectra')
    op.drop_table('spectra')
    op.drop_index(op.f('ix_session_tokens_user_id'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_id'), table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_index(op.f('ix_zeolite_families_id'), table_name='zeolite_families')
    op.drop_index(op.f('ix_zeolite_families_code'), table_name='zeolite_families')
    op.drop_table('zeolite_families')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
