"""zeolite_families: agregar si_al_ratio, pore_size, typical_bands, ring_size, channel_dimensionality, cif_filename

Revision ID: 2401e9b67e1e
Revises: 0ab5aaa1271c
Create Date: 2026-08-09 17:35:41.654721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2401e9b67e1e'
down_revision: Union[str, Sequence[str], None] = '0ab5aaa1271c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zeolite_families', sa.Column('si_al_ratio', sa.String(length=50), nullable=True))
    op.add_column('zeolite_families', sa.Column('pore_size', sa.String(length=100), nullable=True))
    op.add_column('zeolite_families', sa.Column('typical_bands', sa.JSON(), nullable=True))
    op.add_column('zeolite_families', sa.Column('ring_size', sa.String(length=50), nullable=True))
    op.add_column('zeolite_families', sa.Column('channel_dimensionality', sa.String(length=20), nullable=True))
    op.add_column('zeolite_families', sa.Column('cif_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zeolite_families', 'cif_filename')
    op.drop_column('zeolite_families', 'channel_dimensionality')
    op.drop_column('zeolite_families', 'ring_size')
    op.drop_column('zeolite_families', 'typical_bands')
    op.drop_column('zeolite_families', 'pore_size')
    op.drop_column('zeolite_families', 'si_al_ratio')
    # ### end Alembic commands ###
